The TokTok Project goal is to [**reinvent the internet**](vision).

But in the meantime, we are a **focussed** effort to bring high quality privacy
enhancing software to everybody.

<div id="slider">
<div class="slides">
<div class="slider"><div class="image"><img src="img/toktok/chatlist-small.png" /></div></div>
<div class="slider"><div class="image"><img src="img/toktok/chat-small.png" /></div></div>
<div class="slider"><div class="image"><img src="img/toktok/profile-small.png" /></div></div>
<div class="slider"><div class="image"><img src="img/toktok/calling-small.png" /></div></div>
<div class="slider"><div class="image"><img src="img/toktok/search-small.png" /></div></div>
</div>
<div class="switch"><ul><li><div class="on"></div></li><li></li><li></li><li></li><li></li></ul></div>
</div>

# Current focus

Focus means we work on a small set of projects (one or two at a time) and
concentrate all our work on getting those projects finished completely before
moving on to the next target.

Our current focus is:

- Create a [full specification](spec) of the Tox protocol.
- Create a free [reference implementation](https://github.com/TokTok/hstox) of
  that protocol.

# Contact us

If you're interested in what we're doing, feel free to stop by on IRC in
[#toktok on Freenode](irc://irc.freenode.net/#toktok). Feel free to stick
around and discuss TokTok related topics. If you do join, please stay on topic
and respect other people.

You can file bugs against one of the TokTok projects on Github. Build status of
all projects can be viewed on this page.

<table>
<tr>
<th>Project</th>
<th>Build Status</th>
<th>Coverage</th>
<th>Issues</th>
<th>PRs</th>
</tr>
$repos:repo()$
</table>
