<tr>
<td><a href="https://github.com/TokTok/$it.name$">$it.name$</a></td>
<td><a href="https://travis-ci.org/TokTok/$it.name$"><img src="https://api.travis-ci.org/TokTok/$it.name$.svg?branch=master" alt="Build Status"/></a></td>
<td><a href="https://coveralls.io/github/TokTok/$it.name$?branch=master"><img src="https://coveralls.io/repos/github/TokTok/$it.name$/badge.svg?branch=master" alt="Coverage"/></a></td>
<td><a href="https://github.com/TokTok/$it.name$/issues">Issues</a></td>
<td><a href="https://github.com/TokTok/$it.name$/pulls">PRs</a></td>
</tr>
